### ISSUE TITLE
Link bei Extensions zu Github falsch

### ISSUE THREAD

**Issue by zonky2** [iMi-digital/yoast-seo-for-contao#1]
siehe https://extensions.contao.org/?sort=released&p=imi%2Fyoast-seo-for-contao

Link "Quelltext" geht zu https://github.com/imi/yoast-seo-for-contao

**Comment by amenk** [comment]
Danke @zonky2 fürs reporten

**Comment by amenk** [comment]
We will fix this with the next release which will include also #2
